language: java
jdk:
- openjdk17
branches:
  only:
  - main
before_install:
- chmod +x gradlew
before_script:
- echo "==== CHECK DICTIONARY FILE ===="
- ls -al src/main/resources/dictionary
- cat src/main/resources/dictionary/komoran-dictionary.user
- find build -name komoran-dictionary.user
- unzip -l build/libs/*.jar | grep komoran-dictionary.use
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build --info"
notifications:
  email:
    recipients:
    - xoals1417@gmail.com
dd:
- openssl aes-256-cbc -K $encrypted_2f692484526a_key -iv $encrypted_2f692484526a_iv
  -in ./src/test/resources/application.properties.enc -out ./src/test/resources/application.properties -d
- openssl aes-256-cbc -K $encrypted_2f692484526a_key -iv $encrypted_2f692484526a_iv
  -in ./src/main/resources/application.properties.enc -out ./src/main/resources/application.properties -d
- openssl aes-256-cbc -K $encrypted_b846c1a3db1c_key -iv $encrypted_b846c1a3db1c_iv
  -in ./src/main/resources/application-oauth.properties.enc -out ./src/main/resources/application-oauth.properties -d
