language: java
jdk:
- openjdk17
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_84feb29e20d8_key -iv $encrypted_84feb29e20d8_iv
  -in application.properties-test.enc -out ./src/test/resources/application.properties
  -d
- openssl aes-256-cbc -K $encrypted_8d56ecc3da0e_key -iv $encrypted_8d56ecc3da0e_iv
  -in application-oauth.properties-main.enc -out ./src/main/resources/application-oauth.properties
  -d
- openssl aes-256-cbc -K $encrypted_8fd383601570_key -iv $encrypted_8fd383601570_iv
  -in application.properties-main.enc -out ./src/main/resources/application.properties
  -d
- chmod +x gradlew
before_script:
- echo "==== CHECK DICTIONARY FILE ===="
- ls -al src/main/resources/dictionary
- cat src/main/resources/dictionary/komoran-dictionary.user
- find build -name komoran-dictionary.user
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build --info"
notifications:
  email:
    recipients:
    - xoals1417@gmail.com
